{{- include "adp-helm-library.deployment" (list . "ffc-sfd-messages.deployment") -}}
{{- define "ffc-sfd-messages.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "ffc-sfd-messages.container") }}
{{- end -}}
