services:
  ffc-sfd-messages:
    build:
      context: .
      target: production
    image: ffc-sfd-messages
    container_name: ffc-sfd-messages
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-messages-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AUTH_HOST: ${AUTH_HOST:-http://ffc-sfd-proxy:3000}
      GATEWAY_HOST: ${GATEWAY_HOST:-http://localhost:3000}
      DATA_HOST: ${DATA_HOST:-http://ffc-sfd-data:3004/graphql}
      MESSAGES_HOST: ${MESSAGES_HOST:-http://ffc-sfd-messages:3005}
