parameters:
- name: deployFromFeature
  displayName: "Deploy from Feature Branch"
  type: boolean
  default: true

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/heads/main

extends:
  template: /pipelines/common-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    projectName: "ffc-sfd-messages"
    serviceName: "ffc-sfd-messages"
    deployFromFeature: ${{ parameters.deployFromFeature }}
    appBuildConfig:
      appFrameworkType: "nodejs"    
      projectPath: "./package.json"
      manifestPath: "./package.json"
      imageRepoName: "ffc-sfd-messages"
    appTestConfig:
      testFilePath: "./docker-compose.test.yaml"
    appDeployConfig:
      filepath: "./appConfig"  
      filetype: "yaml"
      variableGroups:
        - ffc-sfd-messages-<environment>
