- key: NODE_ENV
  value: "production"
- key: PORT
  value: "3005"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"
- key: DATA_HOST
  value: "http://ffc-sfd-data.fcp-sfd/graphql"
- key: AUTH_HOST
  value: "http://ffc-sfd-auth.fcp-sfd"
- key: MESSAGES_HOST
  value: "http://ffc-sfd-messages-processor.fcp-sfd"