- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: AUTH_HOST
  value: "http://ffc-sfd-auth.fcp-sfd"
- key: GATEWAY_HOST
  value: "https://ffc-sfd-messages.snd3.adp.defra.gov.uk"
- key: DATA_HOST
  value: "http://ffc-sfd-data.fcp-sfd"
- key: MESSAGES_HOST
  value: "https://ffc-sfd-messages-processor.fcp-sfd"
